# Generated by Django 2.2.1 on 2019-06-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyreport', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='epreuve',
            old_name='date_bl',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='affaire',
            name='adresse_1',
            field=models.CharField(max_length=200, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='affaire',
            name='adresse_2',
            field=models.CharField(max_length=200, verbose_name='Complément'),
        ),
        migrations.AlterField(
            model_name='client',
            name='adresse_fact_1',
            field=models.CharField(max_length=200, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='client',
            name='adresse_fact_2',
            field=models.CharField(max_length=200, verbose_name='Complément'),
        ),
        migrations.AlterField(
            model_name='client',
            name='adresse_siege_1',
            field=models.CharField(max_length=200, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='client',
            name='adresse_siege_2',
            field=models.CharField(max_length=200, verbose_name='Complément'),
        ),
        migrations.AlterField(
            model_name='client',
            name='code',
            field=models.CharField(max_length=10, verbose_name='Code ID'),
        ),
        migrations.AlterField(
            model_name='client',
            name='etablissement',
            field=models.CharField(max_length=100, verbose_name='Etablissement'),
        ),
        migrations.AlterField(
            model_name='client',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='epreuve',
            name='d1',
            field=models.FloatField(verbose_name='1ère mesure'),
        ),
        migrations.AlterField(
            model_name='epreuve',
            name='d2',
            field=models.FloatField(verbose_name='2ème mesure'),
        ),
        migrations.AlterField(
            model_name='epreuve',
            name='d3',
            field=models.FloatField(verbose_name='3ème mesure'),
        ),
        migrations.AlterField(
            model_name='epreuve',
            name='rc1',
            field=models.FloatField(verbose_name='1ère éprouvette)'),
        ),
        migrations.AlterField(
            model_name='formule',
            name='denomination',
            field=models.CharField(max_length=100, verbose_name='Dénomination'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
    ]
