# Generated by Django 2.2.1 on 2019-06-12 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easyreport', '0003_auto_20190612_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='epreuve',
            name='h',
            field=models.FloatField(default=None, verbose_name='Hauteur'),
        ),
        migrations.AlterField(
            model_name='epreuve',
            name='d1',
            field=models.FloatField(verbose_name='Diamètre (1)'),
        ),
        migrations.AlterField(
            model_name='epreuve',
            name='d2',
            field=models.FloatField(verbose_name='Diamètre (2)'),
        ),
        migrations.AlterField(
            model_name='epreuve',
            name='d3',
            field=models.FloatField(verbose_name='Diamètre (3)'),
        ),
        migrations.AlterField(
            model_name='epreuve',
            name='num_bl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easyreport.BonLivraison', verbose_name='Numéro de BL'),
        ),
        migrations.AlterField(
            model_name='epreuve',
            name='rc1',
            field=models.FloatField(verbose_name='Epreuve 1'),
        ),
        migrations.AlterField(
            model_name='epreuve',
            name='rc2',
            field=models.FloatField(verbose_name='Epreuve 2'),
        ),
        migrations.AlterField(
            model_name='epreuve',
            name='rc3',
            field=models.FloatField(default=None, verbose_name='Epreuve 3'),
        ),
    ]
