# Generated by Django 2.2.1 on 2019-06-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyreport', '0004_auto_20190612_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonlivraison',
            options={'verbose_name': 'Bon de livraison', 'verbose_name_plural': 'Bons de livraisons'},
        ),
        migrations.AlterField(
            model_name='epreuve',
            name='rc1',
            field=models.FloatField(verbose_name='Epreuve (1'),
        ),
        migrations.AlterField(
            model_name='epreuve',
            name='rc2',
            field=models.FloatField(verbose_name='Epreuve (2)'),
        ),
        migrations.AlterField(
            model_name='epreuve',
            name='rc3',
            field=models.FloatField(default=None, verbose_name='Epreuve (3)'),
        ),
    ]
