# Generated by Django 2.2.1 on 2019-06-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyreport', '0005_auto_20190616_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affaire',
            name='adresse_2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Complément'),
        ),
        migrations.AlterField(
            model_name='client',
            name='adresse_fact_1',
            field=models.CharField(blank=True, max_length=200, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='client',
            name='adresse_fact_2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Complément'),
        ),
        migrations.AlterField(
            model_name='client',
            name='adresse_siege_2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Complément'),
        ),
        migrations.AlterField(
            model_name='client',
            name='commune_fact',
            field=models.CharField(blank=True, max_length=100, verbose_name='Commune'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cp_fact',
            field=models.CharField(blank=True, max_length=10, verbose_name='Code postal'),
        ),
        migrations.AlterField(
            model_name='client',
            name='etablissement',
            field=models.CharField(blank=True, max_length=100, verbose_name='Etablissement'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='etablissement',
            field=models.CharField(blank=True, max_length=100, verbose_name='Etablissement'),
        ),
    ]
